### ISSUE TITLE
Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor

### ISSUE THREAD

**Issue by Neznaykas** [temporalio/sdk-php#264]
Hi! When I try use workflows us

MainWorkflow -> Run ChildWorkflows -> Run ChildWorkflows -> Run Activities

I get error

Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor

if this is the correct behavior, how do I call a non-child workflow?

SDK: v2.3.0
Server: 1.8.5

Trace:
```
{
  "message": "Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor",
  "source": "PHP_SDK",
  "stackTrace": "ReflectionException: Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor in /var/app/vendor/temporal/sdk/src/DataConverter/JsonConverter.php:150\nStack trace:\n#0 /var/app/vendor/temporal/sdk/src/DataConverter/JsonConverter.php(150): ReflectionClass->newInstanceWithoutConstructor()\n#1 /var/app/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53): Temporal\\DataConverter\\JsonConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#2 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(80): Temporal\\DataConverter\\DataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#3 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(Temporal\\DataConverter\\Type))\n#4 /var/app/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#5 /var/app/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#6 /var/app/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#7 /var/app/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#8 /var/app/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#9 /var/app/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#10 /var/app/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#11 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#12 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#13 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n'\\x08\\xA9F*\"\\n \\n\\x16\\n\\x08en...', Array)\n#14 /var/app/worker.php(57): Temporal\\WorkerFactory->run()\n#15 {main}\n\nNext Temporal\\Exception\\DataConverterException: Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor in /var/app/vendor/temporal/sdk/src/DataConverter/JsonConverter.php:152\nStack trace:\n#0 /var/app/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53): Temporal\\DataConverter\\JsonConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#1 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(80): Temporal\\DataConverter\\DataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#2 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(Temporal\\DataConverter\\Type))\n#3 /var/app/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#4 /var/app/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#5 /var/app/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#6 /var/app/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#7 /var/app/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#8 /var/app/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#9 /var/app/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#10 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#11 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#12 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n'\\x08\\xA9F*\"\\n \\n\\x16\\n\\x08en...', Array)\n#13 /var/app/worker.php(57): Temporal\\WorkerFactory->run()\n#14 {main}",
  "encodedAttributes": null,
  "cause": {
    "message": "Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor",
    "source": "PHP_SDK",
    "stackTrace": "ReflectionException: Class Generator is an internal class marked as final that cannot be instantiated without invoking its constructor in /var/app/vendor/temporal/sdk/src/DataConverter/JsonConverter.php:150\nStack trace:\n#0 /var/app/vendor/temporal/sdk/src/DataConverter/JsonConverter.php(150): ReflectionClass->newInstanceWithoutConstructor()\n#1 /var/app/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53): Temporal\\DataConverter\\JsonConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#2 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(80): Temporal\\DataConverter\\DataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#3 /var/app/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(Temporal\\DataConverter\\Type))\n#4 /var/app/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#5 /var/app/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#6 /var/app/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#7 /var/app/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#8 /var/app/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#9 /var/app/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#10 /var/app/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#11 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#12 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#13 /var/app/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n'\\x08\\xA9F*\"\\n \\n\\x16\\n\\x08en...', Array)\n#14 /var/app/worker.php(57): Temporal\\WorkerFactory->run()\n#15 {main}",
    "encodedAttributes": null,
    "cause": null,
    "applicationFailureInfo": {
      "type": "ReflectionException",
      "nonRetryable": false,
      "details": null
    }
  },
  "applicationFailureInfo": {
    "type": "Temporal\\Exception\\DataConverterException",
    "nonRetryable": false,
    "details": null
  }
}
```

**Comment by wolfy-j** [comment]
Please follow the standard bug report template which must include:
- minimal way to reproduce the error
- information about SDK version

**Comment by Neznaykas** [comment]
an approximate path

```
class ParentWorkflow implements ParentWorkflowInterface
{
    public function greet(string $name)
    {
        $child = Workflow::newChildWorkflowStub(ChildWorkflow::class);

        // This is a non blocking call that returns immediately.
        // Use yield $child->greet(name) to call synchronously.
        $childGreet = $child->greet($name);

        // Do something else here.

        return 'Hello ' . $name . ' from parent; ' . yield $childGreet;
    }

class ChildWorkflow
{
    #[WorkflowMethod("Child.greet")]
    public function greet(
        string $name
    ) {

        $child = Workflow::newChildWorkflowStub(SubChildWorkflow::class);

        // This is a non blocking call that returns immediately.
        // Use yield $child->greet(name) to call synchronously.
        $childGreet = $child->greet($name);

        return yield $childGreet;
    }
}

class SubChildWorkflow
{
    #[WorkflowMethod("SubChild.greet")]
    public function greet(
        string $name
    ) {
        return 'Hello ' . $name . ' from child workflow!';
    }
}

```
I'll try to write a better example a little later

**Comment by ruscon** [comment]
Have the same issue.

@Neznaykas Have you found how to solve the problem?

**Comment by Neznaykas** [comment]
Yes, error has if return class Generator in SubChild

maybe it should be

**Comment by rustatian** [comment]
Closing as fixed
