### ISSUE TITLE
[Bug] DataConverter type named "null" is not a valid type name

### ISSUE THREAD

**Issue by root-aza** [temporalio/sdk-php#328]
### Describe the bug

DataConverter not supported types: null, true, false 

stackTrace:

```json
{
    "message": "Type named \"null\" is not a valid type name",
    "source": "PHP_SDK",
    "stackTrace": "Temporal\\Exception\\DataConverterException: Type named \"null\" is not a valid type name in /var/www/api/vendor/temporal/sdk/src/DataConverter/JsonConverter.php:190\nStack trace:\n#0 /var/www/api/vendor/temporal/sdk/src/DataConverter/JsonConverter.php(158): Temporal\\DataConverter\\JsonConverter->errorInvalidTypeName(Object(Temporal\\DataConverter\\Type))\n#1 /var/www/api/src/Infrastructure/Temporal/DataConverter/SymfonySerializerDataConverter.php(54): Temporal\\DataConverter\\JsonConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#2 /var/www/api/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53): App\\Infrastructure\\Temporal\\DataConverter\\SymfonySerializerDataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#3 /var/www/api/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(80): Temporal\\DataConverter\\DataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#4 /var/www/api/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(ReflectionNamedType))\n#5 /var/www/api/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#6 /var/www/api/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#7 /var/www/api/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#8 /var/www/api/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#9 /var/www/api/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#10 /var/www/api/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#11 /var/www/api/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#12 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#13 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#14 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n%\\x08\\xACF* \\n\\x1E\\n\\x16\\n\\x08en...', Array)\n#15 /var/www/api/src/Infrastructure/Temporal/UI/Cli/WorkerCommand.php(37): Temporal\\WorkerFactory->run()\n#16 /var/www/api/vendor/symfony/console/Command/Command.php(312): App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 /var/www/api/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 /var/www/api/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 /var/www/api/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand(Object(App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 /var/www/api/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 /var/www/api/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 /var/www/api/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 /var/www/api/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\ConsoleApplicationRunner->run()\n#24 /var/www/api/bin/console(11): require_once('/var/www/api/ve...')\n#25 {main}",
    "cause": null,
    "applicationFailureInfo": {
        "type": "Temporal\\Exception\\DataConverterException",
        "nonRetryable": false,
        "details": null
    },
    "failureInfo": "applicationFailureInfo"
}

```

### Minimal Reproduction

```php
<?php

#[Activity]
final readonly class VantaBankNotificationActivityHandler implements VantaBankLoanNotificationActivity
{
    public function __construct(
        private LoanNotificationClient $client
    ) {
    }


    /**
     * @throws ClientException
     */
    #[ActivityMethod]
    public function notify(Uid $id, LoanEventType $event, \DateTimeImmutable $date): null
    {
        $this->client->dispatchEvent($id, $event, $date);

        return null;
    }
}
```

### Environment/Versions
- Sdk versions 2.5.1

**Comment by root-aza** [comment]
Hi. problem still exists. 

composer.lock

![Screenshot 2023-07-12 at 13 43 32](https://github.com/temporalio/sdk-php/assets/13816704/5b1759f4-1142-4da1-a070-8a9ac9e8f8e9)


```json
{
  "message": "Type named \"null\" is not a valid type name",
  "source": "PHP_SDK",
  "stackTrace": "Temporal\\Exception\\DataConverterException: Type named \"null\" is not a valid type name in /var/www/api/vendor/temporal/sdk/src/DataConverter/JsonConverter.php:190\nStack trace:\n#0 /var/www/api/vendor/temporal/sdk/src/DataConverter/JsonConverter.php(158): Temporal\\DataConverter\\JsonConverter->errorInvalidTypeName(Object(Temporal\\DataConverter\\Type))\n#1 /var/www/api/src/Infrastructure/Temporal/DataConverter/SymfonySerializerDataConverter.php(53): Temporal\\DataConverter\\JsonConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#2 /var/www/api/vendor/temporal/sdk/src/DataConverter/DataConverter.php(53): App\\Infrastructure\\Temporal\\DataConverter\\SymfonySerializerDataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#3 /var/www/api/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(80): Temporal\\DataConverter\\DataConverter->fromPayload(Object(Temporal\\Api\\Common\\V1\\Payload), Object(Temporal\\DataConverter\\Type))\n#4 /var/www/api/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(ReflectionNamedType))\n#5 /var/www/api/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#6 /var/www/api/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#7 /var/www/api/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#8 /var/www/api/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#9 /var/www/api/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#10 /var/www/api/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#11 /var/www/api/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#12 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#13 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#14 /var/www/api/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n%\\x08\\xAAF* \\n\\x1E\\n\\x16\\n\\x08en...', Array)\n#15 /var/www/api/src/Infrastructure/Temporal/UI/Cli/WorkerCommand.php(37): Temporal\\WorkerFactory->run()\n#16 /var/www/api/vendor/symfony/console/Command/Command.php(312): App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 /var/www/api/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 /var/www/api/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 /var/www/api/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand(Object(App\\Infrastructure\\Temporal\\UI\\Cli\\WorkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 /var/www/api/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 /var/www/api/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 /var/www/api/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 /var/www/api/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\ConsoleApplicationRunner->run()\n#24 /var/www/api/bin/console(11): require_once('/var/www/api/ve...')\n#25 {main}",
  "encodedAttributes": null,
  "cause": null,
  "applicationFailureInfo": {
    "type": "Temporal\\Exception\\DataConverterException",
    "nonRetryable": false,
    "details": null
  }
}
```

**Comment by root-aza** [comment]
@roxblnfk cc

**Comment by roxblnfk** [comment]
@root-aza did you restart RR server after SDK update?
I tested it with that activity
https://github.com/temporalio/sdk-php/blob/894a808d03c256407ad828cceaf18d32fc1a6026/tests/Fixtures/src/Activity/Php82TypesActivity.php#L22

**Comment by root-aza** [comment]
Hhm. Yep. right now it's working 😂
